# -*- coding: utf-8 -*-
"""Despliegue_CalidadAgua_Stremlite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J8NXSvjfh3_8dmtaIOhT7pLXewZi6VtS

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

#Cargamos el modelo
import pickle
filename = 'modelo-clas-hiper.pkl'
modelTree,labelencoder,variables,min_max_scaler = pickle.load(open(filename, 'rb'))
#Tienen que ponerse en el mismo orden que se guardaron

#Cargamos los datos futuros
#data = pd.read_csv("datosFuturosCalidadAgua.csv")
#data.head()

import streamlit as st
import pandas as pd
import plotly.express as px

# --- CONFIGURACIÓN GENERAL ---
st.set_page_config(page_title="Visualización de Calidad del Agua", page_icon="💧", layout="centered", initial_sidebar_state="expanded")

# --- ESTILO PERSONALIZADO ---
st.markdown("""
    <style>
    .main {
        background-color: #f0f8ff; /* AliceBlue */
        color: #2F4F4F; /* DarkSlateGray */
        font-family: 'Arial';
    }
    .stButton>button {
        background-color: #ADD8E6; /* LightBlue */
        color: black;
        border-radius: 12px;
        height: 3em;
        width: 100%;
    }
    .stSlider > div {
        color: #4682B4; /* SteelBlue */
    }
    .stSelectbox > div {
        color: #4682B4; /* SteelBlue */
    }
    .css-1d391kg {
        background-color: #E0FFFF; /* LightCyan */
    }
    </style>
""", unsafe_allow_html=True)

# --- ENCABEZADO ---
st.title("💧 Visualización de Índices de Calidad del Agua")
st.markdown("Explora los niveles de riesgo de calidad del agua por municipio y año.")

# --- CARGA DE DATOS (Simulación con los datos que proporcionaste) ---
data = pd.DataFrame({
    'Departamento': ['Sucre', 'Sucre', 'Tolima', 'Antioquia', 'Antioquia', 'Bolívar'],
    'Municipio': ['Galeras', 'Galeras', 'Rioblanco', 'Medellín', 'Amalfi', 'Santa Rosa'],
    'Año': [2017, 2018, 2013, 2010, 2009, 2011],
    'IRCA': [53.0, 12.0, 11.6, 1.4, 0.7, 27.6],
    'IRCAurbano': [48.5, 12.0, 15.64, 0.5, 0.7, 28.5],
    'Nivel de riesgo urbano': ['Riesgo alto', 'Riesgo bajo', 'Riesgo medio', 'Sin riesgo', 'Sin riesgo', 'Riesgo medio'],
    'IRCArural': [38.53, 38.53, 38.53, 2.6, 38.53, 18.8],
    'Nivel de riesgo rural': ['Riesgo alto', 'Riesgo alto', 'Riesgo alto', 'Sin riesgo', 'Riesgo alto', 'Riesgo medio']
})

# --- FILTROS EN LA BARRA LATERAL ---
st.sidebar.header("Filtros ⚙️")
selected_departamento = st.sidebar.selectbox("Selecciona un Departamento", ['Todos'] + list(data['Departamento'].unique()))
selected_municipio = st.sidebar.selectbox("Selecciona un Municipio", ['Todos'])
selected_año = st.sidebar.selectbox("Selecciona un Año", ['Todos'] + list(data['Año'].unique()))
risk_levels_urbano = ['Todos'] + list(data['Nivel de riesgo urbano'].unique())
selected_riesgo_urbano = st.sidebar.selectbox("Selecciona un Nivel de Riesgo Urbano", risk_levels_urbano)
risk_levels_rural = ['Todos'] + list(data['Nivel de riesgo rural'].unique())
selected_riesgo_rural = st.sidebar.selectbox("Selecciona un Nivel de Riesgo Rural", risk_levels_rural)

# --- FILTRADO DE DATOS ---
filtered_data = data.copy()

if selected_departamento != 'Todos':
    filtered_data = filtered_data[filtered_data['Departamento'] == selected_departamento]

if selected_municipio != 'Todos':
    filtered_data = filtered_data[filtered_data['Municipio'] == selected_municipio]

if selected_año != 'Todos':
    filtered_data = filtered_data[filtered_data['Año'] == selected_año]

if selected_riesgo_urbano != 'Todos':
    filtered_data = filtered_data[filtered_data['Nivel de riesgo urbano'] == selected_riesgo_urbano]

if selected_riesgo_rural != 'Todos':
    filtered_data = filtered_data[filtered_data['Nivel de riesgo rural'] == selected_riesgo_rural]

# --- ACTUALIZACIÓN DEL SELECTOR DE MUNICIPIOS (dependiente del departamento) ---
if selected_departamento != 'Todos':
    municipios = ['Todos'] + list(filtered_data['Municipio'].unique())
    selected_municipio = st.sidebar.selectbox("Selecciona un Municipio", municipios)
    if selected_municipio != 'Todos':
        filtered_data = filtered_data[filtered_data['Municipio'] == selected_municipio]

# --- VISUALIZACIONES ---
st.header("📊 Visualización de los Datos Filtrados")

if filtered_data.empty:
    st.info("No hay datos que coincidan con los filtros seleccionados.")
else:
    # 1. Distribución de Niveles de Riesgo Urbano
    fig_riesgo_urbano = px.bar(filtered_data, x='Municipio', color='Nivel de riesgo urbano',
                               title='Distribución del Nivel de Riesgo Urbano por Municipio',
                               labels={'Nivel de riesgo urbano': 'Nivel de Riesgo Urbano', 'Municipio': 'Municipio'})
    st.plotly_chart(fig_riesgo_urbano)

    # 2. Distribución de Niveles de Riesgo Rural
    fig_riesgo_rural = px.bar(filtered_data, x='Municipio', color='Nivel de riesgo rural',
                              title='Distribución del Nivel de Riesgo Rural por Municipio',
                              labels={'Nivel de riesgo rural': 'Nivel de Riesgo Rural', 'Municipio': 'Municipio'})
    st.plotly_chart(fig_riesgo_rural)

    # 3. Evolución del IRCA Urbano por Año (si hay múltiples años)
    if len(filtered_data['Año'].unique()) > 1:
        fig_irca_urbano_año = px.line(filtered_data, x='Año', y='IRCAurbano', color='Municipio',
                                     title='Evolución del IRCA Urbano por Año y Municipio',
                                     labels={'IRCAurbano': 'IRCA Urbano', 'Año': 'Año', 'Municipio': 'Municipio'})
        st.plotly_chart(fig_irca_urbano_año)

    # 4. Dispersión IRCA Urbano vs. IRCA Rural
    fig_scatter_irca = px.scatter(filtered_data, x='IRCAurbano', y='IRCArural', color='Municipio',
                                  title='Relación entre IRCA Urbano e IRCA Rural',
                                  labels={'IRCAurbano': 'IRCA Urbano', 'IRCArural': 'IRCA Rural', 'Municipio': 'Municipio'})
    st.plotly_chart(fig_scatter_irca)

# --- PIE DE PÁGINA ---
st.markdown("---")
st.markdown("<center><small>🌸 Visualización creada por Shaddai Caballero, Samuel Orrego, Oscar Castaño - 2025</small></center>", unsafe_allow_html=True)

"""**Preparar los datos futuros**"""

#Ya se realizo la preparacion de los datos anteriormente
#Se crean dummies a las variables predictoras categóricas (no a la variable obj)
data_preparada=data.copy()
data_preparada = pd.get_dummies(data, columns=['Departamento','Municipio','Año','Nivel de riesgo urbano', 'Nivel de riesgo rural'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

"""**Prediccion**"""

#Hacemos la predicción con el Tree
Y_fut = modelTree.predict(data_preparada)
data['Tree']=labelencoder.inverse_transform(Y_fut)
data.head()